### ISSUE TITLE
undefined method

### ISSUE THREAD

**Issue by mokkin** [blacksenator/carddav2fb#1]
I have just built the master and get the following error:
```
/var/www/carddav2fb-blacktest$ php carddav2fb.php run -vvv -c nc.php 
Determine the last change of the FRITZ!Box phonebook
Determine the last change(s) on the CardDAV server(s)
PHP Fatal error:  Uncaught Error: Call to undefined method Andig\CardDav\Backend::query() in /var/www/carddav2fb-blacktest/src/CardDav/Backend.php:281
Stack trace:
#0 /var/www/carddav2fb-blacktest/src/functions.php(486): Andig\CardDav\Backend->getModDate()
#1 /var/www/carddav2fb-blacktest/src/RunCommand.php(48): Andig\getlastmodification(Object(Andig\CardDav\Backend))
#2 /var/www/carddav2fb-blacktest/vendor/symfony/console/Command/Command.php(255): Andig\RunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/carddav2fb-blacktest/vendor/symfony/console/Application.php(960): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/carddav2fb-blacktest/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Andig\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co in /var/www/carddav2fb-blacktest/src/CardDav/Backend.php on line 281
```
Details:
```
php -v
PHP 7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0 (cli) (built: Feb  9 2019 06:51:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-1+0~20190209065123.16+stretch~1.gbp3ad8c0, Copyright (c) 1999-2018, by Zend Technologie
```
Any idea what to do?

**Comment by blacksenator** [comment]
Thank you for bringing this to my attention. The master changed two months ago and I obviously forgot to test something after the merge. The function getModDate calls another function (from the master), which was deleted without substitution. I fix that as fast as possible - as long as please for "forcedupload" in the configuration set the value 2 or 3!

**Comment by mokkin** [comment]
Thanks.
forcedupload works and lets me continue.

**Comment by blacksenator** [comment]
Fixed. All three `forced_upload` settings should now work properly again
